GET http://localhost:5000/

###

POST http://localhost:5000/register
Content-Type: application/json

{
    "firstName" : "Sachin",
    "lastName" : "JH",
    "email" : "sachintesting23@gmail.com",
    "password" : "sachintest",
    "enrolledCourses" : [
        {
            "enrolledCourseID" : "62931b43bc292b6b60285041",
            "enrolledCourseName" : "Intro to Web Dev",
            "grade" : 30
        },
        {
            "enrolledCourseID" : "6294bf53e36e2c5a38a3ea8e",
            "enrolledCourseName" : "Intro to ML",
            "grade" : 50
        }
    ]
}

###

GET http://localhost:5000/courses

###

POST http://localhost:5000/newcourse
Content-Type: application/json

{
    "courseName": "Intro to CPP",
    "duration": "60+ Hours",
    "cost": 999,
    "courseDescription": "CPP Description Lorem ipsum dolor sit amet consectetur adipisicing elit. Modi atque consectetur ullam aut pariatur suscipit, officiis nam possimus cupiditate tempora! At ducimus aliquam dolorum ipsa odio, mollitia provident non maxime.",
    "listOfContents": [
        {
        "contentName": "Basics - CPP",
        "video_list": ["Basics 1", "Basics 2", "Basics 3", "Basics 4"]
        },
        {
        "contentName": "Advanced - CPP",
        "video_list": ["Advanced 1", "Advanced 2", "Advanced 3", "Advanced 4", "Advanced 5", "Advanced 6"]
        },
        {
        "contentName": "Application - CPP",
        "video_list": ["Application 1", "Application 2", "Application 3", "Application 4", "Application 5", "Application 6"]
        }
    ],
    "exam": [
        {
            "question": "Question 1",
            "choices": ["Option 1", "Option 2", "Option 3", "Option 4"],
            "answer": "Option 1"
        },
        {
            "question": "Question 2",
            "choices": ["Option 1", "Option 2", "Option 3", "Option 4"],
            "answer": "Option 2"
        },
        {
            "question": "Question 3",
            "choices": ["Option 1", "Option 2", "Option 3", "Option 4"],
            "answer": "Option 3"
        },
        {
            "question": "Question 4",
            "choices": ["Option 1", "Option 2", "Option 3", "Option 4"],
            "answer": "Option 4"
        },
        {
            "question": "Question 5",
            "choices": ["Option 1", "Option 2", "Option 3", "Option 4"],
            "answer": "Option 1"
        },
        {
            "question": "Question 6",
            "choices": ["Option 1", "Option 2", "Option 3", "Option 4"],
            "answer": "Option 2"
        },
        {
            "question": "Question 7",
            "choices": ["Option 1", "Option 2", "Option 3", "Option 4"],
            "answer": "Option 3"
        },
        {
            "question": "Question 8",
            "choices": ["Option 1", "Option 2", "Option 3", "Option 4"],
            "answer": "Option 4"
        },
        {
            "question": "Question 9",
            "choices": ["Option 1", "Option 2", "Option 3", "Option 4"],
            "answer": "Option 1"
        },
        {
            "question": "Question 10",
            "choices": ["Option 1", "Option 2", "Option 3", "Option 4"],
            "answer": "Option 2"
        }

    ]
} 